name: Construye y actualiza contenedor para pruebas en Docker Hub

on:
  push:
    paths:
    - pyproject.toml
    - poetry.lock
    - Dockerfile
    - .github/workflows/build_container.yml
    - README.md

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Comprueba el repositorio
        uses: actions/checkout@v2

      - name: Se logea en DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Obtiene metadatos de docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nachocarher/myhams
          flavor: latest=true

      - name: Construye y hace push de la imagen
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
